name:                suggestion
version:             0.1.0.0
github:              "Skyb0rg007/suggestion"
license:             BSD3
author:              "Skye Soss"
maintainer:          "skyler.soss@gmail.com"
copyright:           "2021 Skye Soss"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Skyb0rg007/suggestion#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- text
- bytestring
- srcloc
- mtl
- transformers

library:
  source-dirs: src
  build-tools:
  - alex
  - happy

executables:
  suggestion-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - suggestion

tests:
  suggestion-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - suggestion
